---
- name: Network config
  copy: src=ifcfg-{{ item }} dest=/etc/sysconfig/network-scripts/ifcfg-{{ item }}
  with_items:
    - eth2
    - eth3
    - eth4

- name: Restart network service
  service: name=network state=restarted enabled=yes

- name: Installing latest version docker
  shell: curl -sSL https://get.docker.io | bash

- name: Install base package
  yum: name={{ item }} state=latest
  with_items:
    - docker-engine
    - python-devel
    - libffi-devel
    - openssl-devel
    - python-pip
    - gcc
    - chrony

- name: Docker config
  template: src=docker.conf.j2 dest=/etc/sysconfig/docker

- name: Change docker service file
  template: src=docker.service.j2 dest=/usr/lib/systemd/system/docker.service

- command: systemctl daemon-reload

- name: Start docker service
  service: name=docker state=restarted enabled=yes

- name: Config ntp serice
  template: src=chrony.conf.j2 dest=/etc/chrony.conf

- name: Restart ntpd service
  service: name=chronyd state=restarted enabled=yes

- pip: name=python-openstackclient

- pip: name=docker-py version=1.6.0

- command: parted /dev/vdb -s -- mklabel gpt mkpart KOLLA_CEPH_OSD_BOOTSTRAP 1 -1
  when: inventory_hostname in groups['storage']

- copy: src=/etc/hosts dest=/etc/hosts
